<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Atualizar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../cadastro.css">
</head>

<body>
    <div class="container">
        <div class="col-12">
            <div class="text-center m-5">
                <?php
                echo '<h1>Atualize o item ' . $id .'</h1>';
                echo '<form action="/atualizarCarro/' . $id . '" method="post"';
                ?>
            </div>
            <div class="row">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text titulo">Modelo</span>
                    </div>
                    <input type="text" name="modelo" placeholder="Modelo" class="form-control" required>
                </div>
            </div>
            <div class="row">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text titulo">Marca</span>
                    </div>
                    <input type="text" name="marca" placeholder="Marca" class="form-control" required>
                </div>
            </div>
            <div class="row">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text titulo">Ano</span>
                    </div>
                    <input type="number" name="ano" placeholder="Ano" class="form-control" required>
                </div>
            </div>
        </div>
        <div class="text-center">
            <input type="submit" class="btn btn-primary" value="Atualizar">
            <a href="/tabela/" class="btn btn-primary">Voltar</a>
        </div>
        </form>
    </div>
</body>

</html>