<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Início</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <form action="/inicio/" method="get">
        <div class="container">
            <div class="col-12">
                <div class="row">
                    <div class="col-10">
                        <h1>Seja bem vindo, <?php echo $_SESSION['login']['nome'] ?>!!!</h1>
                    </div>
                    <div class="col-2">
                        <a href="/sair/" class="btn btn-primary">Sair</a>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="row">
                    <?php
                    foreach ($textos as $key => $texto) {
                        echo '<h1 class="col-sm">' . $texto['titulo'] . '</h1>';
                        echo '<label class="col-sm">' . $texto['texto'] . '</label>';
                    }
                    ?>
                </div>
            </div>
        </div>
    </form>
</body>

</html>