<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tabela</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="shortcut icon" href="../logo.png" type="image/x-icon">
</head>

<body>
    <form action="/tabela/" method="get">
        <div class="container">
            <table class="table table-dark mt-5 mb-5">
                <thead>
                    <tr>
                        <th class="text-center" scope="col">#</th>
                        <th class="text-center" scope="col">Modelo</th>
                        <th class="text-center" scope="col">Marca</th>
                        <th class="text-center" scope="col">Ano</th>
                        <th class="text-center" scope="col">Ação</th>
                        <th class="text-center" scope="col">Ação</th>
                        <th class="text-center" scope="col">Proprietário</th>
                        
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($carros as $key => $carro) {
                        echo '<tr>';
                            echo '<th class="text-center" scope="row">' . $carro['id'] . '</th>';
                            echo '<td class="text-center">' . $carro['modelo'] . '</td>';
                            echo '<td class="text-center">' . $carro['marca'] . '</td>';
                            echo '<td class="text-center">' . $carro['ano'] . '</td>';
                            echo '<td class="text-center"><a href="/editar/' . $carro['id'] . '" class="btn btn-primary">Editar</a></td>';
                            echo '<td class="text-center"><a href="/excluir/' . $carro['id'] . '" class="btn btn-primary">Excluir</a></td>';
                            echo '<td class="text-center">' . $carro['nomeProprietario'] . '</td>';
                        echo '</tr>';
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </form>
</body>

</html>