<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tabela</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <form action="/tabela/" method="get">
        <div class="container">
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Modelo</th>
                        <th scope="col">Marca</th>
                        <th scope="col">Ano</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($carros as $key => $carro) {
                        echo '<tr>';
                            echo '<th scope="row">' . $carro['id'] . '</th>';
                            echo '<td>' . $carro['modelo'] .'</td>';
                            echo '<td>' . $carro['marca'] . '</td>';
                            echo '<td>' . $carro['ano'] . '</td>';
                        echo '</tr>';
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </form>
</body>

</html>